config/routes.rb
Rails.application.routes.draw do

  root 'pages#home', as: 'home'

  get 'users/new'

  get '/new'=> 'users#new' 
  post '/new'=> 'users#create'
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions' => 'sessions#new'
  post 'dashboard' => 'admin#dashboard'
  resources :items
  resource :sessions, only: [:new, :create, :destroy]
  resources :pages, only: [:menu] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'showmsg' => 'messages#showmsg'
  get 'about' => 'pages#about', as: 'about'

  get 'login'=> 'pages#login', as: 'login'
  delete 'logout' => 'sessions#destroy'
  delete 'showmsg' => 'messages#destroy'
  post 'login' => 'sessions#create'
  get 'menu'=> 'pages#menu', as: 'menu'

  get 'contact'=> 'pages#contact', as: 'contact'
  post 'contact' => 'contact#create'
  get 'tocart/:id'=>'pages#tocart', as:'tocart'
  get '/cart', to: 'order_items#index'
  post '/tocart/:id', to: 'order_items#index'
  resources :order_items
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_item_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_item_reduce'
 get 'cart/:id/edit' => 'pages#edit'
  get 'login_admin' => 'admin#login_admin', as: 'login_admin'
 get 'dashboard' => 'admin#dashboard'
  get 'index' => 'items#index', as: 'index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # has_secure_password
  # validates :email, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :title, presence: true
    validates :price, presence: true
    
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user, required: false
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order, required: false
	belongs_to :product, required: false
	
end

app/models/shopping_cart.rb
class ShoppingCart

  delegate :sub_total, to: :order

  def initialize(token:)
    @token = token
    update_sub_total
  end

  def order
    @order ||= Order.find_or_create_by(token: @token) do |order|
      order.sub_total = 0
    end
  end

  def order_item
    @order_item = order.items.find_or_initialize_by(
      item_id: item_id
    )
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(item_id:, quantity: 1, title:)
    product = Item.find(item_id)

    order_item = order.items.find_or_initialize_by(
      item_id: item_id
    )

    order_item.price = product.price
    order_item.quantity = quantity
    order_item.title = product.title
    ActiveRecord::Base.transaction do
    order_item.save
    update_sub_total
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
    order.items.destroy(id)
    update_sub_total
   end
  end

  private

  def update_sub_total
    # puts 'test sub total'
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end


end

app/models/user.rb
class User < ApplicationRecord
	#has_many :messages

	attr_accessor :password

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	

validates :username, :presence => true,
	           :length             => {:maximum => 50}
	validates :email,   :presence => true,  


	           :format             => {:with => email_regex},
			   :uniqueness      => {:case_sensitive => false}

       
	validates :password, :presence => true,
				:confirmation     => true,

 
	           :length             => {:within => 5..40}

	before_save :encrypt_password

	def has_password?(submitted_password)


		encrypted_password == encrypt(submitted_password)
		
	

end

	def self.authenticate(email, submitted_password)
		user = find_by_email(email)

		return nil if user.nil?


		
		return user if user.has_password?(submitted_password)
	end
	

private 
	def encrypt_password

		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?


		self.encrypted_password = encrypt(password)
	end
	def encrypt(pass)
	

Digest::SHA2.hexdigest("#{self.salt}--#{pass}")	
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	def login_admin

    end
end

app/controllers/cart_controller.rb
class Cart

    def initialize(token:)
        @token =token
        end
    def order
        @order ||= Order.find_or_create_by(token: @token) do |order|
            order.sub_total = 0
            end 
end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:remove_image, :title, :description, :image, :price)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
         @items = Item.all
    end

    def login
    end

    def menu
        @items = Item.all
    end
    def cart
        @item = Item.find(params[:id])
       
    end

    def tocart
        @item = Item.find(params[:id])
       
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#	before_action :set_user, only: [:show, :destroy]
 def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to login_path, :notice=> 'User was successfully created'
  	else
  		redirect_to new_path, :notice=> 'Account not created. Try again'
  end
end
  def show
  	@user = User.find(params[:id])
	end
private
	 def user_params
    params.require(:user).permit( :username, :email, :password, :password_confirmation)
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
        self.current_user = user
    end
    def current_user=(user)
        @current_user = user
    end
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def signed_in?
        !current_user.nil?

    end
    def sign_out
        session[:user_id] = nil
        self.current_user = nil

    end
    
    def current_user?(user)
        user == current_user

    end
    def deny_access
        redirect_to login_path, :notice => "Please sign in"
        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/admin/_admin-header.html.erb
<% if current_page?(login_admin_path) || (dashboard_path) %>
    <nav class="navbar  navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= image_tag('my_images/favicon.png') %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Dashboard", login_admin_path%></li>
            
            <%#<li><a href="#contact">Contact</a></li>%>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<%end%>

app/views/admin/dashboard.html.erb
<h1> Dashboard</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3 well">
<table class="table table-bordered" id="#dahboardAdmin">
	<thead>
		<tr>
			<th>S.No.</th>
			<th>Name</th>
		</tr>
	</thead>
	<tbody>
		<tr></tr>
		<tr>
			<td>1</td>
			<td><%= link_to "Items" , index_path %></td>
			</tr>
			<tr>
				<td>2</td>
				<td><%= link_to "Messages" , showmsg_path %></td>
			</tr>

		
			
		
	</tbody>

</table>
</div>
</div>

app/views/admin/login_admin.html.erb
<h1>Log In</h1>
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-md-6 col-md-offset-3 well">

<%= simple_form_for :session, :url =>dashboard_path do |f| %>

	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.submit "Log In"%>

<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyWebsite</title>
    <%= csrf_meta_tags %>
      
    <%= favicon_link_tag('my_images/favicon.png') %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> true %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> 
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    

  </head>

  <body>


   
   <%= render 'pages/header' %>
  

   
    <%= yield %>
   <%= render 'pages/footer' %>

  </body>
</html>

app/views/pages/_footer.html.erb
<% if current_page?(home_path) || current_page?(about_path) || current_page?(login_path) || current_page?(menu_path) || current_page?(contact_path) || current_page?(cart_path) || current_page?(new_path)  %>
<div id="push"></div>
<footer class="text-center footer-front" >
<div class="container">
<div class="row">
<div>Copyright &copy;</div>
</div>
</div>

</footer>
 
 <% else %>
<div id="push"></div>
<footer class="text-center footer-admin" >
<div class="container">
<div class="row">
<div>Copyright &copy;</div>
</div>
</div>

</footer>
<% end %>

app/views/pages/_header.html.erb
 <% if current_page?(home_path) || current_page?(about_path) || current_page?(login_path) || current_page?(menu_path) || current_page?(contact_path) || current_page?(cart_path) || current_page?(new_path)   %>
 <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= image_tag('my_images/favicon.png') %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Menu", menu_path %></li>
            <li><%= link_to "Contact Us", contact_path %></li>
            <li><%= link_to "Cart", cart_path %></li>

          </ul>
           <ul class="nav navbar-nav navbar-right">
            <% if !signed_in? %>
            <li><%= link_to "Log In", login_path %></li>
           
            <li><%= link_to "Sign Up", new_path %></li>
             <% else %>
            <li><%= link_to "Log Out", logout_path, method: "delete" %></li>

            <% if signed_in? %>
            
            <li><a href="#"> Hello, <%= current_user.username %></a></li>
          
          <% end %>
           <% end %>
           <!--  <p id="notice"><%= notice %></p> -->
            <%#<li><a href="#contact">Contact</a></li>%>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <div class="imageMy">
    <div class="bannerImg")>
    </div>
    </div>

    <% else %>
    <nav class="navbar  navbar-default" id="admin-nav">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= image_tag('my_images/favicon.png') %></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="admin-list">
            <li><%= link_to "Dashboard", dashboard_path%></li>
            
            <%#<li><a href="#contact">Contact</a></li>%>
          
        </div><!--/.nav-collapse -->
      </div>
    </nav> 

    <% end %>

app/views/pages/about.html.erb
<h1 class="items-alignment">About Us</h1>

<div class="row">
<div class="col-md-6 col-sm-12">
	<div class="container aboutUsContainer">
	<%= image_tag('my_images/aboutUs.jpg', class:'homeCuisine aboutUsImg image') %>
	<div class="overlay">
		<div class="imageOverlay text">What is Lorem Ipsum?
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
	</div>
	</div>
	</div>
</div>
	<section id="item">
		<br>
		<div class="row">
			<div class="container">
				<div class="col-md-6 col-sm-12  alignButtonShow " >
				<button class="btn btn-default myBtn" ><a href="#" id="showall">Show List</a></button>
			 <div >Top Cuisine
			 </div>
				<div  id="listMenu" >
	
 
					<% @items.each do |item| %>
 
					<p class="item-title"><%= item.title %></p>
  
 
 					<% end %>
				</div>
 				</div>
			</div>
	</section>
</div>

</div>

app/views/pages/cart.html.erb
<%#<div class="hidden" id="show_cart">
Hidden</div>%>
<%= link_to "Back to Menu", menu_path %>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Send us a message</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
<%= form_for Message.new, :url =>contact_path, :method => :post do |form| %>
 <div class="form-group">
    <%= form.label :sender %>
    <%= form.text_field :sender, class:'form-control'%>
  </div>
	 <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class:'form-control', required: true  %>
  </div>


  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class:'form-control', required: true  %>
  </div>

	 <div class="actions">
    <%= form.submit "Submit" %>
  </div>

<% end %>
</div>
</div>

app/views/pages/home.html.erb
<h1 id="homeH1">Top Cuisines</h1>
<div class="container">
<div class="row">
<div class="col-md-3">
<div class="thumb-nail">
<%= image_tag('my_images/food_1.jpg', class:'homeCuisine') %>
<div class="caption">
    <p>Cuisine</p>
</div>
</div>
</div>
<div class="col-md-3">
<div class="thumb-nail">
<%= image_tag('my_images/icecream.jpg', class:'homeCuisine') %>
<div class="caption">
    <p>Cuisine2</p>
</div>
</div>
</div>
<div class="col-md-3">
<div class="thumb-nail">
<%= image_tag('my_images/greenOnion.jpg', class:'homeCuisine') %>
<div class="caption">
    <p>Cuisine3</p>
</div>
</div>
</div>
<div class="col-md-3">
<div class="thumb-nail">
<%= image_tag('my_images/platingfood.jpg', class:'homeCuisine') %>
<div class="caption">
    <p>Cuisine4</p>
</div>
</div>
</div>
</div>
</div>
<div class= "wrapOrderSect">
<h1 id="homeH1">4 Easy Steps to Order Food </h1>
<div class="container">
<div class="row">

<%#<%= image_tag('my_images/food_1.jpg', class:'homeCuisine') %>


<div class="col-md-12 col-xs-3 col-sm-1">
<div class="thumb-nail">
<%= image_tag('my_images/orderfood.png') %>
<%#<div class="caption">
    <p>Step 3</p>
</div>%>
</div>
</div>

</div>
</div>
</div>

app/views/pages/login.html.erb
<h1>Log In</h1>
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6 col-md-offset-3 well">

<%= simple_form_for :session, :url =>sessions_path do |f| %>

	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.submit "Log In"%>

<% end %>
</div>
</div>

app/views/pages/menu.html.erb
<h1 id="menu">Menu</h1>
<div class="container">
<div class="row">
<div class="col-md-3">
<div class="thumb-nail">
<section id="item">
<% @items.each do |item| %>
 <div class="item clearfix">
   <a href="<%= tocart_path(item) %>">
    <div class="item-main">
      <p class="item-title"> 
   
       <%= image_tag item.image.url, class:"item-show" %>
        
</p>
     <span class="item-price"><%= number_to_currency item.price %></span>
   </div>
   <p class="item-title"><%= item.title %></p>
  
 </div>
 <% end %>
</section>

</div>
</div>
</div>
</div>

app/views/pages/tocart.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3 well">

<%= form_for OrderItem.new  do |form|%>
<div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, :value => @item.title , class:'form-control'%>
   
    
  </div>
  <div class="form-group">
    <%= form.label :description %>
     <%= form.text_field :title, :value => @item.description , class:'form-control'%>
    
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= image_tag @item.image.url, class:"item-show form-control" %> 
  </div>
  <div class="form-group">
    <%= form.label :price %>
     <%= form.text_field :title, :value =>  @item.price , class:'form-control'%>
  </div>

<%= form_tag order_items_path do %>
  		<%= hidden_field_tag :item_id, @item.id %>
  		<%= form.label :quantity %>
  		<%= number_field_tag :quantity, 1, class:'form-control' %><br>
  		<%= submit_tag "Add to Cart" %>
  		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  		<% end %> 
<% end %>
  	</div>
  </div>

 