config/routes.rb
Rails.application.routes.draw do

  root 'pages#home', as: 'home'

  get 'users/new'

  get '/new'=> 'users#new' 
  post '/new'=> 'users#create'
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions' => 'sessions#new'
  post 'dashboard' => 'admin#dashboard'
  resources :items
  resource :sessions, only: [:new, :create, :destroy]
  resources :pages, only: [:menu] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'showmsg' => 'messages#showmsg'
  get 'about' => 'pages#about', as: 'about'

  get 'login'=> 'pages#login', as: 'login'
  delete 'logout' => 'sessions#destroy'
  delete 'showmsg' => 'messages#destroy'
  post 'login' => 'sessions#create'
  get 'menu'=> 'pages#menu', as: 'menu'

  get 'contact'=> 'pages#contact', as: 'contact'
  post 'contact' => 'contact#create'
  get 'tocart/:id'=>'pages#tocart', as:'tocart'
  get '/cart', to: 'order_items#index'
  post '/tocart/:id', to: 'order_items#index'
  resources :order_items
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_item_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_item_reduce'
 get 'cart/:id/edit' => 'pages#edit'
  get 'login_admin' => 'admin#login_admin', as: 'login_admin'
 get 'dashboard' => 'admin#dashboard'
  get 'index' => 'items#index', as: 'index' 
end

app/models/item.rb
class Item < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :title, presence: true
    validates :price, presence: true
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:remove_image, :title, :description, :image, :price)
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3 well">
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :item_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, id: :item_image %>
    
     <% if @item.image? %>
     <%= image_tag @item.image.url, class: "item-show" %>
    <%= form.check_box :remove_image %>
    Remove Image
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :item_price, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit %>
  </div>
<% end %>

</div>
</div>

app/views/items/edit.html.erb
<h1 class="items-alignment">Editing Item</h1>

<%= render 'form', item: @item %>

<div class="items-alignment"><%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %></div>

app/views/items/index.html.erb
<p id="notice" class="items-alignment"><%= notice %></p>

<h1 class="items-alignment">Items</h1>
 <div class="items-alignment"><%= link_to 'New Item', new_item_path %> </div>
       
      
<div class="container">
<div class="row">
<div class="col-sm-3 col-lg-6 col-md-offset-3 ">

<table class= "table table-bordered itemIndex" id="itemIndex">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price ($)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><% if item.image? %>
        <%= image_tag item.image.url, class: "item-show" %>
        <% end %>
        </td>
        <td><%= number_to_currency item.price %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete %></td>
      </tr>
    <% end %>
     
  </tbody>
</table>



</div>
</div>
</div>

app/views/items/new.html.erb
<h1 class="items-alignment">New Item</h1>

<%= render 'form', item: @item %>

<div align="center"><%= link_to 'Back', items_path %></div>

app/views/items/show.html.erb
<p id="notice" class="items-alignment"><%= notice %></p>
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">


<table class="table table-stripped itemShow" id="itemShow">
  <thead>
    <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th>Price</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @item.title %></td>
      <td><%= @item.description %></td>
      <td> <% if @item.image? %>
  <%= image_tag @item.image.url, class: "item-show" %>
  <% end %></td>
      <td><%= @item.price %></td>
      <td><%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>
    </tr>
   

  </tbody>
</table>


</div>
</div>