config/routes.rb
Rails.application.routes.draw do

  root 'pages#home', as: 'home'

  get 'users/new'

  get '/new'=> 'users#new' 
  post '/new'=> 'users#create'
  get 'sessions/new' => 'sessions#new'
  post 'sessions/new' => 'sessions#create'
  get 'sessions' => 'sessions#new'
  post 'dashboard' => 'admin#dashboard'
  resources :items
  resource :sessions, only: [:new, :create, :destroy]
  resources :pages, only: [:menu] 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'showmsg' => 'messages#showmsg'
  get 'about' => 'pages#about', as: 'about'

  get 'login'=> 'pages#login', as: 'login'
  delete 'logout' => 'sessions#destroy'
  delete 'showmsg' => 'messages#destroy'
  post 'login' => 'sessions#create'
  get 'menu'=> 'pages#menu', as: 'menu'

  get 'contact'=> 'pages#contact', as: 'contact'
  post 'contact' => 'contact#create'
  get 'tocart/:id'=>'pages#tocart', as:'tocart'
  get '/cart', to: 'order_items#index'
  post '/tocart/:id', to: 'order_items#index'
  resources :order_items
  post 'order_items/:id/add' => 'order_items#add_quantity', as: 'order_item_add'
  post 'order_items/:id/reduce' => 'order_items#reduce_quantity', as: 'order_item_reduce'
 get 'cart/:id/edit' => 'pages#edit'
  get 'login_admin' => 'admin#login_admin', as: 'login_admin'
 get 'dashboard' => 'admin#dashboard'
  get 'index' => 'items#index', as: 'index' 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order, required: false
	belongs_to :product, required: false
	
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

	def index
    	@curr_cart_items = current_cart.order.items
  	end

    def create
        current_cart.add_item(
      		item_id: params[:item_id],
      		quantity: params[:quantity],
          title: params[:title]
    	)
         	redirect_to cart_path
	end
   def update
    if current_cart.update_item(id: params[:id])
      redirect_to tocart_path
  end
end
	def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end

  def add_quantity
    current_cart.increase_quantity(id: params[:id])

    redirect_to cart_path 
  end

  def add_quantity
    @curr_cart_item = OrderItem.find(params[:id]) 
    @curr_cart_item.quantity +=1
    @curr_cart_item.save
    
    redirect_to cart_path 
  end
  
   def reduce_quantity
    @curr_cart_item = OrderItem.find(params[:id]) 
    if @curr_cart_item.quantity > 1 
      @curr_cart_item.quantity -=1
    end
    @curr_cart_item.save
    # update_sub_total
    redirect_to cart_path 
  end

   def order_item_params
      params.require(:order_item).permit(:item, :quantity, :title, :order_id, :item_id )
    end 
end

app/views/order_items/index.html.erb
<br>
<h2>Current Cart</h2>
<div class="container">
<div class="row">
<div class="col-sm-12 col-lg-6 col-md-12 ">
<div >
 <button class="btn-default"><%= link_to "Back to Menu", menu_path %> </button>

<button class="btn-Primary"><%= link_to pluralize(current_cart.items_count, ' item'), cart_path %></button>
 </div>
   <br> 
<table class="table table-bordered orderItems" id="orderIndex">
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="2" align="center">Edit Quantity</th>
      <td></td>
     
      <!-- <th colspan="1"></th> -->
    </tr>
  </thead>
  <tbody>
    <% @curr_cart_items.each do |cart_item| %>
  
      <tr>
       <td><%= cart_item.title %></td>
        <td><%= number_to_currency cart_item.price %></td>
        <td><%= cart_item.quantity %></td>
        
        
        <td><%= link_to "Add one(+)", order_item_add_path(:id => cart_item), method: :post %></td>
        <td><%= link_to "Reduce one", order_item_reduce_path(:id => cart_item), method: :post %></td> 
        <td><%= form_for cart_item, method: :delete  do |f|%>
          <%= f.submit "Remove" %>
          <% end %>
 
        </td>

 
      </tr>
     
    <% end %>

  </tbody>
 
</table>
 <button class="btn btn-primary subTotal" >Total: <%= number_to_currency current_cart.sub_total %> </button>

 </div>
</div>
</div>
</div>